version: '3'

services:
  database:
    build: ./Database
    container_name: database
    restart: always
    ports:
     - "9000:9000"
    volumes:
      - ./Database/src/main/resources:/app/data  # Mount the resources directory of your Database to /app/data in the container
    networks:
      custom_network:
        ipv4_address: 192.168.1.106
networks:
  custom_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24